s="Tops Technologies"

print(s)
print(len(s))
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.swapcase())
print("python programming".title())
print(s.center(40,"&"))
print(s.count("T"))
print(s.endswith("esw"))
print(s.find("log"))
print(s.index("T",2))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print(s.istitle())
print("".isspace())
print("Hello".replace("l","w"))
